#!/usr/bin/env bash

if ! cd /mnt/download/Scans/; then
  echo "Exiting because QNAP Shares are not mounted."
  exit 1;
fi

mv -n img*/* . || true

selectDirectory() {
  local new_name="$1";
  local current_name="$2";
  local target_dir=/home/erik/Documents
  fd --type d . "$target_dir" | \
    fzf \
    --header "ESC=skip    TAB=replace query    CTRL+N=use prompt as new directory    ALT+E: edit current PDF (replace file!)" \
    `# CTRL-N: create folder and reload directory list, TAB: replace query with current selection, ALT+E: open in libreoffice` \
    --bind "ctrl-n:execute-silent(mkdir -p {fzf:query})+reload-sync(fd --type d . \"$target_dir\"),tab:replace-query,alt-e:execute-silent(simpress \"$current_name\" &)" \
    --preview "ls --color=always -lsa {}" \
    --preview-label "Directory listing" \
    --prompt "Select destination for $new_name  > " \
  || true
}

for pdf in *.pdf; do
  fn=$(basename "$pdf" | cut -d '.' -f 1 | sed 's/\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/20\1-\2-\3T\4-\5-\6/');
  ocr_pdf="$fn-ocr.pdf"
  if ! ocrmypdf -l deu "$pdf" "$ocr_pdf"; then
    continue;
  fi
  
  rip "$pdf"

  xdg-open "$ocr_pdf" 2> /dev/null;

  echo "To fixup the OCRed file, press ALT+E in the target directory selection."

  read -r -p "New name for $ocr_pdf (leave blank to skip, file extension added automatically):"$'\n' new_name
  if [ -z "$new_name" ]; then
    echo "Skipping $ocr_pdf";
    continue;
  fi
  
  new_name="${new_name}.pdf"
  dest=$(selectDirectory "$new_name" "$ocr_pdf");
  if [ -z "$dest" ]; then
    echo "Skipping $new_name";
    mv -i "$ocr_pdf" "$new_name";
  else
    echo "Moving $ocr_pdf to $dest/$new_name";
    mv -i "$ocr_pdf" "$dest/$new_name";
  fi
done

fd --type d "img.*" --max-depth 1 --exec rmdir
