name: "Update custom packages"

# inspired by https://github.com/dee0sap/ocm/blob/7f814d567f7d0cece733e2e142c57a6adf96459b/.github/workflows/flake_vendorhash.yaml

on:
  schedule:
    # Runs 02:50 every Saturday.
    - cron: "50 2 * * 6"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        pkg:
          - "koi"
          - "patreon-dl"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: nix-env -i git-crypt -f '<nixpkgs>'
      - name: Detect new version
        id: detect-new-version
        run: |
          HAS_VERSION_CHECKER="$(nix eval .#packages --impure -I nixpkgs=channel:nixpkgs-unstable --apply 'pkgs:
            let
              lib = (import <nixpkgs> {}).lib;
              pkg = pkgs.${builtins.currentSystem}.${{ matrix.pkg }};
            in
              lib.attrsets.hasAttrByPath [ "passthru" "custom" "newVersionCheck"] pkg
          ')";
          CURRENT_SYSTEM="$(nix eval --impure --expr 'builtins.currentSystem')"
          echo "CURRENT_SYSTEM=$CURRENT_SYSTEM" >> "$FORGEJO_ENV"
          if [ "$HAS_VERSION_CHECKER" = 'true' ]; then
            SCRIPT="$(nix build .#packages.${CURRENT_SYSTEM}.${{ matrix.pkg }}.passthru.custom.newVersionCheck --print-out-paths)"
            echo "NEW_VERSION=$($SCRIPT)" >> "$FORGEJO_ENV"
          else
            echo "NEW_VERSION=stable" >> "$FORGEJO_ENV"
          fi
      - name: Apply version update
        id: apply-version-update
        run: |
          NIX_PATH="nixpkgs=channel:nixpkgs-unstable" nix run nixpkgs#nix-update -- \
            --write-commit-message "commit.txt" \
            --file ./pkgs/impure.nix \
            --version ${NEW_VERSION} \
            ${{ matrix.pkg }}
          {
            echo "COMMIT_MSG<<EOF"
            OLD_VERSION="$( sed -n 's/.*: \(.*\) -> .*/\1/;1p' < commit.txt )"
            sed '1s/\([^:]*\): \(.*\)/chore(\1): \2/;'"s-/None\.\.\.-/${OLD_VERSION}...-" < commit.txt
            echo EOF
            echo "DIFF_COMPARE=$( sed -n '/^Diff: / s/Diff: \(.*\)/\1/p' < commit.txt )"
            echo "NEW_VERSION=$( sed -n 's/.*: .* -> \(.*\)/\1/;1p' < commit.txt )"
            echo "UPSTREAM_URL=$(nix eval .#packages.${CURRENT_SYSTEM}.${{ matrix.pkg }}.meta.homepage --raw)"
          } >> "$FORGEJO_OUTPUT";
      - name: Check diff
        id: check-diff
        run: |
          diff=$(git diff -- pkgs/${{ matrix.pkg }})
          if [[ -z "$diff" ]]; then
            echo "No package updated."
            echo "PACKAGE_UPDATED=false" >> "$FORGEJO_OUTPUT"
            exit 0
          fi

          echo "PACKAGE_UPDATED=true" >> "$FORGEJO_OUTPUT"

          cat << EOF >> "${FORGEJO_STEP_SUMMARY}"
          \`\`\`diff
          ${diff}
          \`\`\`
          EOF

          {
            echo 'body<<EOF'
            echo '```diff'
            echo "$diff"
            echo '```'
            echo EOF
          } >> "$FORGEJO_OUTPUT"
      - name: Create pull request
        id: create_pull_request
        uses: https://github.com/maxking/forgejo-create-pr
        #uses: https://github.com/maxking/forgejo-create-pr@40a9fc1008252e082053cda0fc00d4cc38814056
        with:
          token: ${{ secrets.NIX_CONFIG_OPEN_PR }}
          commit-message: ${{ steps.apply-version-update.outputs.COMMIT_MSG }}
          pr-title: Update ${{ matrix.pkg }} to ${{ steps.apply-version-update.outputs.NEW_VERSION }}
          body: |
            This PR was automatically created by CI job [update-custom-pkgs.yml](${{ forgejo.server_url }}/${{ forgejo.repository }}/blob/${{ forgejo.ref }}/.forgejo/workflows/update-custom-pkgs.yml).
            Run the updated program directly from the PR for testing:

            ```bash
            nix run git+https://codeberg.org/ede1998/nix-config?ref=update-${{ matrix.pkg }}#${{ matrix.pkg }}
            ```

            Upstream URL: <${{ steps.apply-version-update.outputs.UPSTREAM_URL }}>
            Version Diff URL: <${{ steps.apply-version-update.outputs.DIFF_COMPARE }}>

            Diff:

            ${{ steps.check-diff.outputs.body }}
          pr-branch: update-${{ matrix.pkg }}
          pr-automerge: true
          commit-user: Flake Bot
          commit-email: actions@codeberg.org
          pr-assignee: ede1998
          author: Flake Bot <actions@github.com>
          add-paths: |
            pkgs/${{ matrix.pkg }}
          base: master
