#!/usr/bin/env bash

set errexit
set pipefail
set nounset

# Load nixpkgs into the current shell
# Basically what nix shell <installable> does but without sub-shell
nix-load() {
	local s=""
	local cmd="$1"
	local installable="$2"
	if command -v "$cmd" 2>&1 >/dev/null; then
		return 0
	fi
	local p="$(nix build --no-link --print-out-paths $installable)"
	export PATH="$p/bin:$PATH"
}

nix-load find nixpkgs#findutils
nix-load sed nixpkgs#gnused
nix-load git nixpkgs#git

REPO_ROOT=$(git rev-parse --show-toplevel)

# secrets => secrets-dummy replication
find "$REPO_ROOT/secrets" -type f |
	while read -r src; do
		dest=$(sed 's:/secrets/:/secrets-dummy/:' <<<"$src")
		content="TOKEN for $src"
		if [ ! -f "$dest" ]; then
			echo "$content" >"$dest"
		fi
	done

# secrets-dummy => secrets replication
find "$REPO_ROOT/secrets-dummy" -type f |
	while read -r src; do
		dest=$(sed 's:/secrets-dummy/:/secrets/:' <<<"$src")
		if [ ! -f "$dest" ]; then
			echo "TODO" >"$dest"
		fi
	done
