{ pkgs, ... }:
{
  home.packages = with pkgs; [
    bat
    blender
    cargo-asm
    cargo-binutils
    cargo-bloat
    cargo-edit
    cargo-espmonitor
    cargo-expand
    cargo-outdated
    cargo-udeps
    cargo-update
    cura5
    dig
    dust
    ede1998-utilities
    element-desktop
    exif
    fclones
    fd
    file
    gcc
    gimp
    git-crypt
    glxinfo
    gnumake
    htop
    hunspell
    hunspellDicts.de_DE
    hunspellDicts.en_US
    inkscape
    inxi
    jq
    jqp
    kdePackages.filelight
    kdePackages.kcalc
    kdePackages.kdepim-addons
    kdePackages.krdc
    kdePackages.krfb
    libreoffice-fresh
    nix-tree
    p7zip
    pciutils
    pdfarranger
    pdfpc
    pinentry
    piper
    psmisc
    ripgrep
    rust-script
    rustup
    texliveFull
    tldr
    traceroute
    tree
    typst
    ungoogled-chromium
    unstable.espup
    (unstable.identity.overrideAttrs (super: self: { meta.priority = 1; })) # fix collision with mesa-demos
    unstable.ocrmypdf
    unstable.rip2
    unzip
    ventoy-full
    viu
    vlc
    wireshark
    wl-clipboard-rs
    xmlstarlet
    xsv
    yq
    zip
  ];
}
